### ISSUE TITLE
Integration tests broken in ember-rocks 0.9.5

### ISSUE THREAD

**Issue by Haroldchen** [mattma/ember-rocks#13]
I generated a new project with version 0.9.5 and tried to run ´em t´ to see if the tests were working correctly since I was having problems in an earlier version as well. It looks like the test cannot find the App variable or something in the start-app helper isn't working as expected. 

Here is the output that I'm getting from ´em t´:

```
Integration -
Home - '/' -
"before each" hook ‣
TypeError: undefined is not a function
    at startApp (http://localhost:7357/tests/tests.js:30:28)
    at Context.<anonymous> (http://localhost:7357/tests/tests.js:96:13)
    at callFn (http://localhost:7357/tests/assets/scripts/mocha.js:4496:21)
    at Hook.Runnable.run (http://localhost:7357/tests/assets/scripts/mocha.js:4489:7)
    at next (http://localhost:7357/tests/assets/scripts/mocha.js:4777:10)
    at http://localhost:7357/tests/assets/scripts/mocha.js:4794:5
    at timeslice (http://localhost:7357/tests/assets/scripts/mocha.js:6218:27)
"after each" hook ‣
TypeError: Cannot read property 'destroy' of undefined
    at Context.<anonymous> (http://localhost:7357/tests/tests.js:100:25)
    at callFn (http://localhost:7357/tests/assets/scripts/mocha.js:4496:21)
    at Hook.Runnable.run (http://localhost:7357/tests/assets/scripts/mocha.js:4489:7)
    at next (http://localhost:7357/tests/assets/scripts/mocha.js:4777:10)
    at http://localhost:7357/tests/assets/scripts/mocha.js:4794:5
    at timeslice (http://localhost:7357/tests/assets/scripts/mocha.js:6218:27)
```

Can you confirm that it isn't currently working?

**Comment by mattma** [comment]
It does not work at the moment. `ember v1.10` has some major changes on templates, and test-helpers has also changed dramatically. The previous implementation does not transfer automatically and some major work is needed in the testing space. 

Help is needed

**Comment by mattma** [comment]
Read [here](https://github.com/mattma/ember-rocks/issues/13#issuecomment-90802250)
